os: osx
language: cpp
before_install:
    - brew update
    - brew install boost || true 
    - brew install yaml-cpp || true
    - brew install pip || true
    - pip install tabulate
install:
script:
    - ./waf configure build

